[sensor]
filename = sensor.dat

[filter]
# Options: moving_average, moving_,median, low_pass
type = moving_median
window_size = 5
alpha = 0.3

[controller]
threshold = 50.0

[main]
poll_interval_ms = 100